version: '3'
services:
  #授权服务
  mogu_search:
    image: registry.cn-hangzhou.aliyuncs.com/ckpblog/mogu_search:latest
    container_name: mogu_search
    restart: always
    ports:
      - 8605:8605
    networks:
      - mogu
    environment:
      - COMPOSE_PROJECT_NAME=mogu_search
    volumes:
      - ../log/:/logs/
networks:
  mogu:
    external: true